# Generated by Django 2.2.7 on 2019-11-27 05:20

import IungoClientDashboard.models
import IungoClientDashboard.validations
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('date_time', models.DateField(blank=True, null=True, verbose_name='Actual BRS Start Date')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_appointment', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_appointment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='child_sub_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IungoClientDashboard.Category')),
            ],
        ),
        migrations.CreateModel(
            name='WalkinCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=70, verbose_name='email')),
                ('mobile_phone', models.CharField(max_length=10, null=True, unique=True, verbose_name='Mobile phone')),
                ('date_time', models.DateField(blank=True, null=True, verbose_name='Actual BRS Start Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='sub_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IungoClientDashboard.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=30, verbose_name='Project Name')),
                ('project_description', models.CharField(max_length=250, verbose_name='Project Description')),
                ('last_modified', models.DateField(default=None, null=True)),
                ('file_size', models.CharField(max_length=20)),
                ('project_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IungoClientDashboard.child_sub_category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50)], max_length=10, verbose_name='Experience')),
                ('qualification', models.CharField(choices=[('UG', 'UNDER GRADUATE'), ('G', 'GRADUATE'), ('PG', 'POST GRADUATE'), ('PhD', 'PhD')], max_length=20, verbose_name='Qualification')),
                ('budget', models.CharField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59), (60, 60), (61, 61), (62, 62), (63, 63), (64, 64), (65, 65), (66, 66), (67, 67), (68, 68), (69, 69), (70, 70), (71, 71), (72, 72), (73, 73), (74, 74), (75, 75), (76, 76), (77, 77), (78, 78), (79, 79), (80, 80), (81, 81), (82, 82), (83, 83), (84, 84), (85, 85), (86, 86), (87, 87), (88, 88), (89, 89), (90, 90), (91, 91), (92, 92), (93, 93), (94, 94), (95, 95), (96, 96), (97, 97), (98, 98), (99, 99), (100, 100)], max_length=20, verbose_name='Budget')),
                ('prefix', models.CharField(choices=[('MR', 'MR'), ('MRS', 'MRS'), ('MS', 'MS'), ('MX', 'MX')], max_length=3, verbose_name='Prefix')),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=10, verbose_name='Gender')),
                ('mobile_phone', models.CharField(max_length=10, null=True, unique=True, verbose_name='Mobile phone')),
                ('secondary_phone', models.CharField(max_length=10, null=True, unique=True, verbose_name='Secondary phone')),
                ('tel_phone', models.CharField(max_length=10, null=True, unique=True, verbose_name='Tele phone')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('about_me', models.CharField(blank=True, max_length=250, verbose_name='About me ')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=IungoClientDashboard.models.content_file_name, verbose_name='Profile Picture')),
                ('location', models.CharField(max_length=30, verbose_name='location')),
                ('client', models.BooleanField(default=0, verbose_name='Client')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks', models.CharField(max_length=10, verbose_name='clicks')),
                ('date_time', models.DateField(blank=True, null=True, verbose_name='Actual BRS Start Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvoicesProposalsUploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoices', models.FileField(upload_to=IungoClientDashboard.models.change_file_path, validators=[IungoClientDashboard.validations.validate_file_extension], verbose_name='Invoices')),
                ('proposals', models.FileField(upload_to=IungoClientDashboard.models.change_file_path, validators=[IungoClientDashboard.validations.validate_file_extension], verbose_name='Proposals')),
                ('date_time', models.DateField(blank=True, null=True, verbose_name='Actual BRS Start Date')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_invoice_and_proposals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_invoice_and_proposals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeedBackRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=250, verbose_name='Feedback')),
                ('rating', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=5, verbose_name='rating')),
                ('date_time', models.DateField(blank=True, null=True, verbose_name='Actual BRS Start Date')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Customer_feedback', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_feedback', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_name', models.CharField(max_length=30, verbose_name='Design project Name')),
                ('design_description', models.CharField(max_length=250, verbose_name='Design Description')),
                ('last_modified', models.DateField(default=None, null=True)),
                ('file_size', models.CharField(max_length=20)),
                ('design_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IungoClientDashboard.child_sub_category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeisgnUploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_name', models.CharField(max_length=30, verbose_name='Design project Name')),
                ('design_images', models.FileField(upload_to=IungoClientDashboard.models.content_file_name)),
                ('date_time', models.DateField(blank=True, null=True, verbose_name='Actual BRS Start Date')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_designs', to=settings.AUTH_USER_MODEL)),
                ('design_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IungoClientDashboard.child_sub_category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_designs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='child_sub_category',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IungoClientDashboard.sub_category'),
        ),
        migrations.CreateModel(
            name='AppointmentScheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slots_booked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IungoClientDashboard.Appointment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
