# Generated by Django 2.2.7 on 2019-12-02 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IungoClientDashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='IungoClientDashboard.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='IungoClientDashboard.sub_category'),
            preserve_default=False,
        ),
    ]
