# Generated by Django 2.2.7 on 2019-12-05 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IungoClientDashboard', '0003_auto_20191204_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='tel_phone',
        ),
    ]
