# Generated by Django 2.2.7 on 2019-12-09 06:24

import IungoClientDashboard.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('IungoClientDashboard', '0004_remove_portfolio_tel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='design_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IungoClientDashboard.sub_category'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='budget',
            field=models.CharField(choices=[('0-10', '0-10'), ('11-20', '11-20'), ('21-30', '21-30'), ('31-40', '31-40'), ('41-50', '41-50'), ('51-60', '51-60'), ('61-70', '61-70'), ('71-80', '71-80'), ('81-90', '81-90'), ('91-100', '91-100')], max_length=20, verbose_name='Budget'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IungoClientDashboard.sub_category'),
        ),
        migrations.CreateModel(
            name='UserUploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=IungoClientDashboard.models.content_file_name, verbose_name='Image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
