# Generated by Django 2.2.7 on 2019-12-09 06:31

import IungoClientDashboard.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('IungoClientDashboard', '0005_auto_20191209_0624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='design_images',
        ),
        migrations.AddField(
            model_name='design',
            name='design_images',
            field=models.ManyToManyField(to='IungoClientDashboard.UserUploads'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_images',
        ),
        migrations.CreateModel(
            name='UserUploadsProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=IungoClientDashboard.models.content_file_name, verbose_name='Image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='project_images',
            field=models.ManyToManyField(to='IungoClientDashboard.UserUploadsProject'),
        ),
    ]
